### ISSUE TITLE
ViperMonkey IOCs included from Previous Submissions

### ISSUE THREAD

**Issue by malvidin** [CybercentreCanada/assemblyline-service-vipermonkey#6]
ViperMonkey results appear additive to previous submissions.

After submitting DOTM malware that contained domain and URL IOCs extracted with ViperMonkey, the next DOTM ViperMonkey result contained the previous file's domain and URL IOCs, along with the new domain and URL IOCs from the new file.

cccs/assemblyline-service-vipermonkey:4.0.0.beta4

**Comment by cccs-jp** [comment]
This issue has been resolved in the stable8 release. Thanks @cccs-jh
